EXT_STATIC =
EXT_SHARED =
EXT_LIBS =
EXT_LTLIBS =
prefix = /usr/local
exec_prefix = $(prefix)
libdir = ${exec_prefix}/lib
prefix = /usr/local
phplibdir = /home/george/src/apd/modules
PHP_COMPILE = $(LIBTOOL) --mode=compile $(COMPILE) -c $<
CC = gcc
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS = -DHAVE_CONFIG_H
CXX =
DEFS =
EXTENSION_DIR = /usr/local/lib/php/extensions/no-debug-non-zts-20001222
EXTRA_LDFLAGS =
EXTRA_LIBS =
INCLUDES = -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/Zend -I/usr/local/include/php/TSRM
LEX =
LEX_OUTPUT_ROOT =
LFLAGS =
SHARED_LIBTOOL = $(LIBTOOL)
LIBTOOL = $(SHELL) $(top_builddir)/libtool
SHELL = /bin/sh
